title: Ben Wilson
subtitle: Writes
venue: Virginia
email: ben@merovex.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter: merovex
facebook: MerovexPress
cdn_url: https://d1czp97ry8if6j.cloudfront.net

future: false
sass:
  style: compressed
collections:
  books:
    output: true
    permalink: /books/:path/

licenses:
  CC0:
    tag: "CC0"
    url: "https://creativecommons.org/share-your-work/public-domain/cc0/"
  PD:
    tag: "Public Domain"
    url: "https://creativecommons.org/share-your-work/public-domain/cc0/"
  RR:
    tag: "Rights Reserved"
    url: "#"
  BY:
    tag: "CC BY 2.0"
    url: "https://creativecommons.org/licenses/by/2.0/"
  BY-SA:
    tag: "CC BY-SA 2.0"
    url: "https://creativecommons.org/licenses/by-sa/2.0/"
  BY-ND:
    tag: "CC BY-ND 2.0"
    url: "https://creativecommons.org/licenses/by-nd/2.0/"

defaults:
  - scope:
      path: ""
      type: "books"
    values:
      layout: "book"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "page"
# Build settings
permalink: /posts/:title
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo
  - jekyll-postcss
  - jekyll-purgecss

# Markdown Processing
kramdown:
  input                   : GFM
  hard_wrap               : false
  auto_ids                : true
  footnote_nr             : 1
  entity_output           : as_char
  toc_levels              : 2..4
  smart_quotes            : lsquo,rsquo,ldquo,rdquo
  syntax_highlighter_opts:
    disable               : true

exclude:
  - node_modules/
  - yarn.lock
  - postcss.config.js
  - tailwind.config.js
  - purgecss.config.js
  - package.json
  - assets/css-old