'Audible' = 'fab fa-audible'
'Paperback' = 'fad fa-book-open'
'Kindle' = 'fad fa-tablet-android-alt'
"Books" = "fad fa-books"
"Bio" = "fad fa-id-card"
"Blog" = "fad fa-newspaper"
"Copyright" = "far fa-copyright"
"Venue" = "far fa-laugh"
"Inbox" = "fad fa-inbox-in"
